AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
  - 'vendor/**/*'

Naming/FileName:
  Exclude:
  - bundler-console.gemspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
